CREATE SCHEMA IF NOT EXISTS `simplewebdatabase` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci; 

CREATE TABLE IF NOT EXISTS `simplewebdatabase`.`product` (
  `CODE` VARCHAR(20) NOT NULL,
  `NAME` VARCHAR(128) NOT NULL,
  `PRICE` FLOAT NOT NULL,
  PRIMARY KEY (`CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `simplewebdatabase`.`user_account` (
  `USER_NAME` VARCHAR(30) NOT NULL,
  `GENDER` VARCHAR(1) NOT NULL,
  `PASSWORD` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`USER_NAME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
